-- -*- mode: lua -*-
file = {
  "lib/init.lua",
  "lib/algo/Array.lua",
  "lib/algo/List.lua",
  "lib/algo/Stack.lua",
  "lib/algo/Queue.lua",
  "lib/algo/Iterator.lua",
  "lib/algo/Map.lua",
  "lib/algo/Set.lua",
  "lib/algo/Heap.lua",
  "lib/algo/NaiveBSTree.lua",
  "lib/algo/Vector.lua",
  "lib/algo/DoubleVector.lua",
  "lib/algo/String.lua",
  "lib/algo/LuaString.lua",
  "lib/algo/UTF8String.lua",
}

project = "algo"
format = "markdown"
examples = { 'test' }
